spring.application.name=rag-mini-project

############################## Ollama #################################
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=mistral
spring.ai.ollama.embedding.options.model=mxbai-embed-large

######################## Vector-DB Initialization  ######################

spring.datasource.url=${DB_URL:jdbc:mariadb://localhost:3307/rag}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root1234}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.ai.vectorstore.mariadb.initialize-schema=true
spring.ai.vectorstore.mariadb.distance-type=COSINE
spring.ai.vectorstore.mariadb.dimensions=1536

####################### Chat-Memory Initialization  #######################

spring.ai.chat.memory.repository.jdbc.initialize-schema=always